# Generated by Django 5.2.13 on 2026-05-10 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DSMTask",
            fields=[
                (
                    "dsm_task_id",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("dsm_id", models.CharField(max_length=255)),
                ("name", models.CharField(max_length=255)),
                ("media_url", models.URLField(blank=True, max_length=500, null=True)),
                (
                    "media_local_path",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                (
                    "media_type",
                    models.CharField(
                        choices=[
                            ("video", "Video"),
                            ("image", "Image"),
                            ("gif", "GIF"),
                        ],
                        default="image",
                        max_length=10,
                    ),
                ),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("ended_at", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "dsm_task",
                "ordering": ["-created_at"],
            },
        ),
    ]
