# Generated by Django 5.2.13 on 2026-05-10 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="dsmtask",
            name="task_type",
            field=models.CharField(
                choices=[
                    ("ALERTHIGHT", "Alert High"),
                    ("ALERTMEDIUM", "Alert Medium"),
                    ("ALERTLOW", "Alert Low"),
                    ("PUBLICRELATION", "Public Relation"),
                ],
                default="PUBLICRELATION",
                max_length=20,
            ),
        ),
    ]
