# Generated by Django 5.2.13 on 2026-05-30 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0003_alter_dsmtask_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dsmtask",
            name="ended_at",
        ),
        migrations.RemoveField(
            model_name="dsmtask",
            name="started_at",
        ),
        migrations.AddField(
            model_name="dsmtask",
            name="date_end_at",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="dsmtask",
            name="date_started_at",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="dsmtask",
            name="time_end_at",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="dsmtask",
            name="time_started_at",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="dsmtask",
            name="timezone",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
