# Generated by Django 5.2.13 on 2026-05-30 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0004_remove_dsmtask_ended_at_remove_dsmtask_started_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dsmtask",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("downloaded", "Downloaded"),
                    ("playing", "playing"),
                    ("skiping", "skiping"),
                    ("completed", "Completed"),
                    ("failed", "Failed"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
