# Generated by Django 5.2.13 on 2026-05-30 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0005_alter_dsmtask_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dsmtask",
            name="created_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="dsmtask",
            name="updated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
