# Generated by Django 5.2.13 on 2026-05-31 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0006_alter_dsmtask_created_at_alter_dsmtask_updated_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dsmtask",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name="dsmtask",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
