# Generated by Django 5.2.13 on 2026-05-31 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0007_alter_dsmtask_created_at_alter_dsmtask_updated_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="OutboxReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("topic", models.CharField(max_length=255)),
                ("payload", models.TextField()),
                ("attempts", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "outbox_report",
                "ordering": ["created_at", "id"],
            },
        ),
    ]
